window.LCE_BIBLE = {
  version: "Bíblia Sagrada Ave-Maria",
  versionCode: "AVM",
  youVersionId: 4542,
  readBase: "https://www.bible.com/pt/bible/4542/",
  audioUrl: "https://www.bible.com/pt/audio-bible-app-versions/4542-avm-b%C3%ADblia-sagrada-ave-maria",

  books: [
    {id:"GEN",name:"Gênesis",testament:"AT",chapters:50},
    {id:"EXO",name:"Êxodo",testament:"AT",chapters:40},
    {id:"LEV",name:"Levítico",testament:"AT",chapters:27},
    {id:"NUM",name:"Números",testament:"AT",chapters:36},
    {id:"DEU",name:"Deuteronômio",testament:"AT",chapters:34},
    {id:"JOS",name:"Josué",testament:"AT",chapters:24},
    {id:"JDG",name:"Juízes",testament:"AT",chapters:21},
    {id:"RUT",name:"Rute",testament:"AT",chapters:4},
    {id:"1SA",name:"I Samuel",testament:"AT",chapters:31},
    {id:"2SA",name:"II Samuel",testament:"AT",chapters:24},
    {id:"1KI",name:"I Reis",testament:"AT",chapters:22},
    {id:"2KI",name:"II Reis",testament:"AT",chapters:25},
    {id:"1CH",name:"I Crônicas",testament:"AT",chapters:29},
    {id:"2CH",name:"II Crônicas",testament:"AT",chapters:36},
    {id:"EZR",name:"Esdras",testament:"AT",chapters:10},
    {id:"NEH",name:"Neemias",testament:"AT",chapters:13},
    {id:"TOB",name:"Tobias",testament:"AT",chapters:14},
    {id:"JDT",name:"Judite",testament:"AT",chapters:16},
    {id:"EST",name:"Ester",testament:"AT",chapters:16},
    {id:"1MA",name:"I Macabeus",testament:"AT",chapters:16},
    {id:"2MA",name:"II Macabeus",testament:"AT",chapters:15},
    {id:"JOB",name:"Jó",testament:"AT",chapters:42},
    {id:"PSA",name:"Salmos",testament:"AT",chapters:150},
    {id:"PRO",name:"Provérbios",testament:"AT",chapters:31},
    {id:"ECC",name:"Eclesiastes",testament:"AT",chapters:12},
    {id:"SNG",name:"Cântico dos Cânticos",testament:"AT",chapters:8},
    {id:"WIS",name:"Sabedoria",testament:"AT",chapters:19},
    {id:"SIR",name:"Eclesiástico",testament:"AT",chapters:51},
    {id:"ISA",name:"Isaías",testament:"AT",chapters:66},
    {id:"JER",name:"Jeremias",testament:"AT",chapters:52},
    {id:"LAM",name:"Lamentações",testament:"AT",chapters:5},
    {id:"BAR",name:"Baruc",testament:"AT",chapters:6},
    {id:"EZK",name:"Ezequiel",testament:"AT",chapters:48},
    {id:"DAN",name:"Daniel",testament:"AT",chapters:14},
    {id:"HOS",name:"Oseias",testament:"AT",chapters:14},
    {id:"JOL",name:"Joel",testament:"AT",chapters:4},
    {id:"AMO",name:"Amós",testament:"AT",chapters:9},
    {id:"OBA",name:"Abdias",testament:"AT",chapters:1},
    {id:"JON",name:"Jonas",testament:"AT",chapters:4},
    {id:"MIC",name:"Miqueias",testament:"AT",chapters:7},
    {id:"NAM",name:"Naum",testament:"AT",chapters:3},
    {id:"HAB",name:"Habacuc",testament:"AT",chapters:3},
    {id:"ZEP",name:"Sofonias",testament:"AT",chapters:3},
    {id:"HAG",name:"Ageu",testament:"AT",chapters:2},
    {id:"ZEC",name:"Zacarias",testament:"AT",chapters:14},
    {id:"MAL",name:"Malaquias",testament:"AT",chapters:3},

    {id:"MAT",name:"São Mateus",testament:"NT",chapters:28},
    {id:"MRK",name:"São Marcos",testament:"NT",chapters:16},
    {id:"LUK",name:"São Lucas",testament:"NT",chapters:24},
    {id:"JHN",name:"São João",testament:"NT",chapters:21},
    {id:"ACT",name:"Atos dos Apóstolos",testament:"NT",chapters:28},
    {id:"ROM",name:"Romanos",testament:"NT",chapters:16},
    {id:"1CO",name:"I Coríntios",testament:"NT",chapters:16},
    {id:"2CO",name:"II Coríntios",testament:"NT",chapters:13},
    {id:"GAL",name:"Gálatas",testament:"NT",chapters:6},
    {id:"EPH",name:"Efésios",testament:"NT",chapters:6},
    {id:"PHP",name:"Filipenses",testament:"NT",chapters:4},
    {id:"COL",name:"Colossenses",testament:"NT",chapters:4},
    {id:"1TH",name:"I Tessalonicenses",testament:"NT",chapters:5},
    {id:"2TH",name:"II Tessalonicenses",testament:"NT",chapters:3},
    {id:"1TI",name:"I Timóteo",testament:"NT",chapters:6},
    {id:"2TI",name:"II Timóteo",testament:"NT",chapters:4},
    {id:"TIT",name:"Tito",testament:"NT",chapters:3},
    {id:"PHM",name:"Filêmon",testament:"NT",chapters:1},
    {id:"HEB",name:"Hebreus",testament:"NT",chapters:13},
    {id:"JAS",name:"São Tiago",testament:"NT",chapters:5},
    {id:"1PE",name:"I São Pedro",testament:"NT",chapters:5},
    {id:"2PE",name:"II São Pedro",testament:"NT",chapters:3},
    {id:"1JN",name:"I São João",testament:"NT",chapters:5},
    {id:"2JN",name:"II São João",testament:"NT",chapters:1},
    {id:"3JN",name:"III São João",testament:"NT",chapters:1},
    {id:"JUD",name:"São Judas",testament:"NT",chapters:1},
    {id:"REV",name:"Apocalipse",testament:"NT",chapters:22}
  ],

  planSource: "Plano de leitura bíblica de 365 dias — organização própria do projeto",
  planOrder: [
    {book:"1JN"},{book:"JHN"},{book:"MRK"},
    {book:"GAL"},{book:"EPH"},{book:"PHP"},{book:"COL"},{book:"1TH"},{book:"2TH"},{book:"1TI"},{book:"2TI"},{book:"TIT"},{book:"PHM"},
    {book:"LUK"},{book:"ACT"},{book:"ROM"},{book:"MAT"},{book:"1CO"},{book:"2CO"},{book:"HEB"},{book:"JAS"},{book:"1PE"},{book:"2PE"},{book:"2JN"},{book:"3JN"},{book:"JUD"},{book:"REV"},

    {book:"WIS"},{book:"SIR"},{book:"PRO"},{book:"PSA"},

    {book:"GEN"},{book:"EXO"},{book:"NUM"},{book:"JOS"},{book:"JDG"},{book:"1SA"},{book:"2SA"},{book:"1KI"},{book:"2KI"},
    {book:"AMO"},{book:"HOS"},
    {book:"ISA",from:1,to:39,label:"Isaías 1–39"},
    {book:"MIC"},{book:"NAM"},{book:"ZEP"},{book:"HAB"},{book:"JER"},{book:"LAM"},{book:"EZK"},{book:"OBA"},
    {book:"ISA",from:40,to:55,label:"Isaías 40–55"},
    {book:"1CH"},{book:"2CH"},{book:"EZR"},{book:"NEH"},{book:"HAG"},{book:"ZEC"},
    {book:"ISA",from:56,to:66,label:"Isaías 56–66"},
    {book:"MAL"},{book:"JOL"},{book:"JON"},{book:"RUT"},{book:"TOB"},{book:"JDT"},{book:"EST"},
    {book:"SNG"},{book:"JOB"},{book:"ECC"},{book:"1MA"},{book:"2MA"},{book:"BAR"},{book:"DAN"},{book:"LEV"},{book:"DEU"}
  ]
};

